INSERT INTO CART(C_NO, C_QTY, P_NO, M_ID) VALUES(CART_C_NO_SEQ.NEXTVAL, 1, 1, 'guard');

INSERT INTO CART(C_NO, C_QTY, P_NO, M_ID) VALUES(CART_C_NO_SEQ.NEXTVAL, 1, 2, 'guard');

INSERT INTO CART(C_NO, C_QTY, P_NO, M_ID) VALUES(CART_C_NO_SEQ.NEXTVAL, 1, 3, 'guard');