
--CART_SELECT_BY_USERID
SELECT C.*, P.* FROM CART C JOIN PRODUCT P ON C.P_NO = P.P_NO WHERE M_ID = 'guard';

--CART_SELECT_BY_CART_NO
SELECT * FROM CART C JOIN PRODUCT P ON C.P_NO = P.P_NO WHERE C_NO = 9;

--CART_COUNT_BY_USERID_PRODUCT_NO
SELECT COUNT(*) AS P_COUNT FROM CART WHERE M_ID = 'guard' AND P_NO = 1;

--CART_DELETE_BY_CART_NO
DELETE FROM CART WHERE C_NO = 9;

--CART_DELETE_BY_USERID
DELETE FROM CART WHERE M_ID = 'guard';

--CART_UPDATE_BY_CART_NO
UPDATE CART SET C_QTY = 2 WHERE C_NO = 9;

--CART_UPDATE_BY_PRODUCT_NO_USERID
UPDATE CART SET C_QTY = C_QTY + 3 WHERE M_ID = 'guard' AND P_NO = 1;